name: Test
on: push
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.SPIN_KEY }}" > .env
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test